
name: Create release from tag

# Controls when the action will run.
# Triggered by git push --tags
# events for the main branch
on:
  push:
    tags:
      - 'v*.*.*'


jobs:

  New release:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Get version from ref
        id: get-version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Create new release
        env:
          GITHUB_TOKEN: ${{ secrets.test_git_key }}
        run: |
          echo -- List variables:
          export TAG=${{ steps.get-version.outputs.VERSION }}
          echo -- New tag:       $TAG
          export NOTES="Release "$TAG" auto created by Actions."
          export TITLE="Release "$TAG
          echo -- Release title: $TITLE
          echo -- Release note:  $NOTES
          echo -- GITHUB_ACTOR:  $GITHUB_ACTOR
          echo --------
          gh config set git_protocol https
          echo -- gh check status
          gh auth status
          echo -- create release
          gh release create $TAG --notes "$NOTES" --title "$TITLE"


