# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    tags:
      - 'v*.*.*'

env:
  GITHUB_TOKEN: ${{ secrets.test_git_key }}
  GITHUB_TOKEN1: "1234567890-1234567890=1234567890+"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Get version from ref
        id: get-version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Run a multi-line script
        run: |
          echo "##" List variables:
          export TAG=${{ steps.get-version.outputs.VERSION }}
          echo "##" New tag: $TAG
          export NOTES="Release "$TAG" auto created. $GITHUB_ACTOR."
          export TITLE="Release "$TAG
          echo "##" Release title: $TITLE
          echo "##" Release note: $NOTES
          echo "##" GITHUB_ACTOR: $GITHUB_ACTOR
          echo --------
          echo $GITHUB_CONTEXT
          echo --------
          gh config set git_protocol https
          # gh auth login --with-token < <(echo "$GITHUB_TOKEN")
          echo "##" gh check status
          gh auth status
          echo "##" create release
          gh release create $TAG --notes '$NOTES' --title '$TITLE'


